### ISSUE TITLE
Using mapped volumes

### ISSUE THREAD

**Issue by ScarlitoDoBrazil** [tuxgasy/docker-dolibarr#107]
Hi.
I'm trying tu use mapped volumes so I can keep data outside of the container and back them up. Unfortunately, I must be missing something as it doesn't work (the html folder stay desperately empty.
Any idea of what I'm doing wrong ?
Everything works well if I remove the "volumes" part for the "web" service (but of course, that's not what I need, as data would stay inside the container).

Here is an example of my docker-compose.yaml file :
```
version: "3"

services:
    mariadb:
        image: mariadb:latest
        environment:
            MYSQL_DATABASE: dolibarr
            MYSQL_USER: my_user
            MYSQL_PASSWORD: my_password
            MYSQL_RANDOM_ROOT_PASSWORD: 1
        volumes:
          - ./db:/var/lib/mysql

    web:
        image: tuxgasy/dolibarr
        environment:
            DOLI_DB_HOST: mariadb
            DOLI_DB_NAME: dolibarr
            DOLI_DB_USER: my_user
            DOLI_DB_PASSWORD: my_password
            DOLI_URL_ROOT: 'http://0.0.0.0'
            DOLI_INSTALL_AUTO: 1
            PHP_INI_DATE_TIMEZONE: 'Europe/Paris'
        ports:
            - 8089:80
        links:
            - mariadb
        volumes:
            - ./html:/var/www/html
            - ./docs:/var/www/documents
```

Thanks for your help.
