### ISSUE TITLE
docker-dolibar with traefik does not work, error 504 gateway timeout

### ISSUE THREAD

**Issue by phu-akensys** [tuxgasy/docker-dolibarr#121]
Hello guys,

I tried to deploy an instance of dolibarr with traefik but it does not seem to work.
I both go to https://my.domain.com and https://my.domain.com/install but it always return 504 Gateway Timeout.
Here is my docker-compose.yml
```
networks:
  default:
    external:
      name: gateway
  backend-isolated:
    name: backend-isolated
    internal: true

volumes:
  dolibarr-custom:
  dolibarr-docs:
  mysql-data:

services:
  dolibarr:
    image: tuxgasy/dolibarr:latest
    container_name: dolibarr_sv
    environment:
      DOLI_DB_HOST: "mysql"
      DOLI_DB_USER: "dolibarr"
      DOLI_DB_PASSWORD: "mypassword"
      DOLI_DB_NAME: "dolibarr"
      DOLI_ADMIN_LOGIN: "admin"
      DOLI_ADMIN_PASSWORD: "mypassword"
    labels:
      - traefik.enable=true
      - traefik.http.routers.dolibarr.rule=Host(`my.domain.com`)
      - traefik.http.routers.dolibarr.entrypoints=websecure
      - traefik.http.routers.dolibarr.tls.certresolver=letsEncrypt
      - traefik.http.services.dolibarr.loadbalancer.server.port=80
    volumes:
      - dolibarr-docs:/var/www/documents
      - dolibarr-custom:/var/www/html/custom
    networks:
      - default
      - backend-isolated

  mysql:
    image: library/mariadb:latest
    container_name: dolibarr_db
    environment:
      MYSQL_DATABASE: "dolibarr"
      MYSQL_USER: "dolibarr"
      MYSQL_PASSWORD: "mypassword"
      MYSQL_ROOT_PASSWORD: "mypassword"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend-isolated
```

Can you guys help me to figure out the problem pls ?
Thank you in advance.
