### ISSUE TITLE
Error: Table 'dolibarr.llx_user' doesn't exist

### ISSUE THREAD

**Issue by Mohamed-Hammada** [tuxgasy/docker-dolibarr#125]
I encountered an error while trying to log in to my Dolibarr application after running it with Docker Compose. The error message states: "Table `dolibarr.llx_user` doesn't exist."

Steps to Reproduce:

1- Set up the Docker Compose configuration with the provided YAML file.
2- Run the Docker Compose command: `docker-compose up`.

Expected Behavior:
After running the Docker Compose command, I expect to be able to log in to the Dolibarr application without any errors.

Actual Behavior:
Upon trying to log in, I receive the error message: "Table 'dolibarr.llx_user' doesn't exist."

Additional Information:
```
version: "3.8"

networks:
  internal-pod:
    internal: true
  external-pod:
    internal: false

volumes:
  dolibarr-custom:
  dolibarr-docs:
  mysql-data:

services:
  dolibarr:
    image: tuxgasy/dolibarr:latest
    environment:
      DOLI_DB_HOST: "mysql"
      DOLI_DB_HOST_PORT: "3306"
      DOLI_DB_USER: "dolibarr"
      DOLI_DB_PASSWORD: "mysupersecretpasswordfordatabase"
      DOLI_DB_NAME: "dolibarr"
      DOLI_ADMIN_LOGIN: "admin"
      DOLI_ADMIN_PASSWORD: "mysuperhypersecretpasswordforadminacount"
    ports:
      - 80:80
    volumes:
      - dolibarr-docs:/var/www/documents
      - dolibarr-custom:/var/www/html/custom
    networks:
      - internal-pod
      - external-pod

  mysql:
    image: library/mariadb:latest
    environment:
      MYSQL_DATABASE: "dolibarr"
      MYSQL_USER: "dolibarr"
      MYSQL_PASSWORD: "mysupersecretpasswordfordatabase"
      MYSQL_ROOT_PASSWORD: "mysupersupersecretpasswordforrootuser"
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - internal-pod
      - external-pod
```
