### ISSUE TITLE
502 when setting cron

### ISSUE THREAD

**Issue by Antoine2tt** [tuxgasy/docker-dolibarr#136]
Hi ! 

Here's my docker compose.yml ; 

```
  web:
    image: tuxgasy/dolibarr:18
    environment:
      DOLI_DB_HOST: bdd
      DOLI_DB_USER: secretUser
      DOLI_DB_PASSWORD: SomeSecretDB
      DOLI_DB_NAME: SecretName
      DOLI_URL_ROOT: SecretURL
      PHP_INI_DATE_TIMEZONE: 'Europe/Paris'
      DOLI_INSTALL_AUTO: 1
      DOLI_CRON: 1
      DOLI_CRON_KEY: Key Generated from the config cron tab in dolibarr
      DOLI_CRON_USER: UserNameOfMyAccount
      DOLI_INSTANCE_UNIQUE_ID: SomeSecretID
```

When i start Dolibarr (i'm using CloudFlare Tunnel), i got 502 Bad gateway 
When removing every "cron" related environment, it works 

Looking the log (with Dozzle), nothing here... 

Have you got any idea ? 
Thanks !
