### ISSUE TITLE
mysql Help. 

### ISSUE THREAD

**Issue by R0dri** [tuxgasy/docker-dolibarr#34]
Even though the db has initialized correctly, docker logs shows
 
> Waiting that SQL database is up ...

Probably a docker container-networking trouble. This is the docker-compose file I'm running:

```
networks:
    internal-pod:
        internal: true
    external-pod:
        internal: false

 services:
    web:
        image: tuxgasy/dolibarr
        environment:
            DOLI_DB_HOST: 172.29.0.2:3306
            DOLI_DB_USER: root
            DOLI_DB_PASSWORD: root
            DOLI_DB_NAME: dolibarr
            DOLI_URL_ROOT: 'localhost'
            PHP_INI_DATE_TIMEZONE: 'Europe/Paris'
        ports:
            - "80:80"
        links:
            - mysql

    mysql:
        image: mysql:8
        restart: always
        environment:
            MYSQL_DATABASE: dolibarr
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_RANDOM_ROOT_PASSWORD: '1'
        volumes:
            - mysql:/Users/rodri/Documents/5sites/testing/db
        cap_add:
            - SYS_NICE

```

When I run the main docker-compose.yml with Maria db it works ok.
