### ISSUE TITLE
There is a DOLI_DB_HOST_PORT ?

### ISSUE THREAD

**Issue by MkLHX** [tuxgasy/docker-dolibarr#40]
Hi, 

I'm trying to use this docker image. Everything works well on first use.

But now i'm trying to migrate db dump and documents from standalone dolibarr V8 old instance.

My containers are launched and run but dolibarr app can't connect to mysql db.

i'm getting this error: ``` | Waiting that SQL database is up ... ```

My docker-compose.yml:
```
version: "3.4"
services:
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        env_file: .env
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABSE}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - ./data:/var/lib/mysql
#            - ./mysqldump/mysqldump.sql:/docker-entrypoint-initdb.d
        ports:
            - "${MYSQL_HOST_PORT:-3306}:3306"
        networks:
            - net
    app:
        image: tuxgasy/dolibarr
        restart: always
        env_file: .env
        environment:
#            DOLI_DB_HOST: db:${MYSQL_HOST_PORT:-3306}
            DOLI_DB_HOST: db
            DOLI_DB_USER: ${MYSQL_USER_DOLIBARR}
            DOLI_DB_PASSWORD: ${MYSQL_PWD_DOLIBARR}
            DOLI_DB_NAME: ${MYSQL_DATABSE}
            DOLI_URL_ROOT: 'https://dolibarr2.greenponik.com'
            PHP_INI_DATE_TIMEZONE: 'Europe/Paris'
            DOLI_INSTALL_AUTO: 1
        volumes:
            - ./logs/:/var/logs/
        ports:
            - "8080:80"
        depends_on:
            - db
        networks:
            - net
networks:
    net:
```
inside my .env:
```
MYSQL_HOST_PORT=33061
```
i don't know if it's possible to change DOLI_DB_HOST port because on my server a local mysql instance is running and already use port: 3306

I tried to force port on DOLI_DB_HOST: db:33061 but no success
