### ISSUE TITLE
http://0.0.0.0/ displays just “It works”

### ISSUE THREAD

**Issue by dbitouze** [tuxgasy/docker-dolibarr#85]
Thanks for providing this Docker image for Dolibarr!

I followed scrupulously [your instructions](https://github.com/tuxgasy/docker-dolibarr#how-to-run-this-image-) and first faced the following error:
```
$ docker-compose up -d
Creating network "dolibarr_default" with the default driver
Pulling mariadb (mariadb:latest)...
latest: Pulling from library/mariadb
405f018f9d1d: Pull complete
7a85079b8234: Pull complete
579c7ff691b1: Pull complete
4976663b5d6d: Pull complete
169024b1fb13: Pull complete
c0ffe8ce897f: Pull complete
b583c09d23c3: Pull complete
9b9f0c08d08f: Pull complete
9cd51f984586: Pull complete
d9f506bb8aca: Pull complete
24d689f79ba4: Pull complete
Digest: sha256:88fcb7d92c7f61cd885c4d309c98461f3607aa6dbd57a2474be86e1956b36d13
Status: Downloaded newer image for mariadb:latest
Pulling web (tuxgasy/dolibarr:)...
latest: Pulling from tuxgasy/dolibarr
c32ce6654453: Pull complete
f244825368f6: Pull complete
0cb682e3d268: Pull complete
eea16ce02660: Pull complete
ca5b7334d364: Pull complete
ecbba56d4063: Pull complete
3822be6520ec: Pull complete
41c523c319c9: Pull complete
dd95c10f64f7: Pull complete
5f82f352ea51: Pull complete
fd46f7727d7b: Pull complete
34450d986a45: Pull complete
c398811107d9: Pull complete
2cd2a3698cea: Pull complete
ee34b1df1b48: Pull complete
8fdb6897cd86: Pull complete
6d58bd679f1f: Pull complete
Digest: sha256:7c7788bf2bc19f565fdb66103ddf8893a935e8ffe14e63d337ed758f75af1c37
Status: Downloaded newer image for tuxgasy/dolibarr:latest
Creating dolibarr_mariadb_1 ... done
Creating dolibarr_web_1     ... 
Creating dolibarr_web_1     ... error

ERROR: for dolibarr_web_1  Cannot start service web: driver failed programming external connectivity on
endpoint dolibarr_web_1 (443bedb8604371044a0be08ce1950aedaaf3d7d78572af356d23e16abacaf029):
Error starting userland proxy: listen tcp4 0.0.0.0:80: bind: address already in use

ERROR: for web  Cannot start service web: driver failed programming external connectivity on endpoint
dolibarr_web_1
(443bedb8604371044a0be08ce1950aedaaf3d7d78572af356d23e16abacaf029): Error starting userland proxy:
listen tcp4
0.0.0.0:80: bind: address already in use
Encountered errors while bringing up the project.
```
I managed by stopping the `httpd` service on my Linux box (Mageia 8) and retrying:
```
$ docker-compose up -d      
dolibarr_mariadb_1 is up-to-date
Recreating dolibarr_web_1 ... done
```
But, now, when I visit http://0.0.0.0/, it displays just “It works” instead to bring me to the new Dolibarr installation. I tried to visit http://0.0.0.0/dolibarr but it doesn't exist.

Thanks in advance for any hint.

**Comment by LaplancheMaxime** [comment]
Hi,
Can you check that you don't already have a stack with a port 80 on your machine? 
  - With this command : `docker ps`. Checked if a container is not already on port 80. If no container is binded on port 80, do you have a web server on your machine ( except docker) ? If so, your port is unavailable.

Proposed solution  : In your compose file, you can change the binded port to 8080 for example: 
```yml
version: "3"

services:
    mariadb:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: dolibarr

    web:
        image: tuxgasy/dolibarr
        environment:
            DOLI_DB_HOST: mariadb
            DOLI_DB_USER: root
            DOLI_DB_PASSWORD: root
            DOLI_DB_NAME: dolibarr
            DOLI_URL_ROOT: 'http://0.0.0.0:8080'
            PHP_INI_DATE_TIMEZONE: 'Europe/Paris'
        ports:
            - "8080:80"
        links:
            - mariadb
```
I haven't tested it, but normally you should be able to access your instance from: `http://0.0.0.0:8080/`

I strongly advise you to use this kind of configuration to expose your applications on your machine: https://dev.to/flemssound/development-enviroment-with-docker-and-traefik-1lg6

Good luck
